In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = pd.read_csv('house_prices.csv')

In [4]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [15]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,65.0,8450,Inside,Gtl,CollgCr,Norm,Norm,1Fam,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,80.0,9600,FR2,Gtl,Veenker,Feedr,Norm,1Fam,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,68.0,11250,Inside,Gtl,CollgCr,Norm,Norm,1Fam,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,60.0,9550,Corner,Gtl,Crawfor,Norm,Norm,1Fam,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,84.0,14260,FR2,Gtl,NoRidge,Norm,Norm,1Fam,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [19]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,65.0,8450,Gtl,CollgCr,Norm,Norm,1Fam,2Story,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,80.0,9600,Gtl,Veenker,Feedr,Norm,1Fam,1Story,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,68.0,11250,Gtl,CollgCr,Norm,Norm,1Fam,2Story,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,60.0,9550,Gtl,Crawfor,Norm,Norm,1Fam,2Story,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,84.0,14260,Gtl,NoRidge,Norm,Norm,1Fam,2Story,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [20]:
del data ['Neighborhood']

In [22]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,LandSlope,Condition1,Condition2,BldgType,HouseStyle,OverallQual,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,65.0,8450,Gtl,Norm,Norm,1Fam,2Story,7,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,80.0,9600,Gtl,Feedr,Norm,1Fam,1Story,6,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,68.0,11250,Gtl,Norm,Norm,1Fam,2Story,7,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,60.0,9550,Gtl,Norm,Norm,1Fam,2Story,7,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,84.0,14260,Gtl,Norm,Norm,1Fam,2Story,8,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [23]:
del data['LandSlope']

In [24]:
del data['Condition1']

In [25]:
del data['Condition2']

In [26]:
del data['BldgType']

In [27]:
del data['HouseStyle']

In [28]:
del data['SaleCondition']

In [29]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,Gable,CompShg,...,61,0,0,0,0,0,2,2008,WD,208500
1,2,20,80.0,9600,6,8,1976,1976,Gable,CompShg,...,0,0,0,0,0,0,5,2007,WD,181500
2,3,60,68.0,11250,7,5,2001,2002,Gable,CompShg,...,42,0,0,0,0,0,9,2008,WD,223500
3,4,70,60.0,9550,7,5,1915,1970,Gable,CompShg,...,35,272,0,0,0,0,2,2006,WD,140000
4,5,60,84.0,14260,8,5,2000,2000,Gable,CompShg,...,84,0,0,0,0,0,12,2008,WD,250000

In [30]:
del data['RoofStyle']

In [31]:
del data['RoofMatl']

In [32]:
del data['SaleType']

In [51]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,Exterior2nd,...,GarageCond,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,VinylSd,VinylSd,...,TA,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,MetalSd,MetalSd,...,TA,298,0,0,0,0,0,0,5,2007
2,3,60,68.0,11250,7,5,2001,2002,VinylSd,VinylSd,...,TA,0,42,0,0,0,0,0,9,2008
3,4,70,60.0,9550,7,5,1915,1970,Wd Sdng,Wd Shng,...,TA,0,35,272,0,0,0,0,2,2006
4,5,60,84.0,14260,8,5,2000,2000,VinylSd,VinylSd,...,TA,192,84,0,0,0,0,0,12,2008

In [36]:
y = data['SalePrice']
del data['SalePrice']

In [35]:
from sklearn.model_selection import train_test_split

In [41]:
Xtrain,Xtest,Ytrain,Ytest = train_test_split(data,y,test_size=0.2)

In [39]:
Xtrain.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,Exterior2nd,...,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
29,30,30,60.0,6324,4,6,1927,1950,MetalSd,MetalSd,...,Y,49,0,87,0,0,0,0,5,2008
765,766,20,75.0,14587,9,5,2008,2008,VinylSd,VinylSd,...,Y,0,174,0,0,0,0,0,8,2008
1397,1398,70,51.0,6120,5,8,1920,2004,MetalSd,MetalSd,...,N,24,0,150,0,0,0,0,5,2007
1149,1150,70,50.0,9000,7,9,1920,1988,VinylSd,VinylSd,...,Y,0,0,0,0,0,0,0,7,2009
79,80,50,60.0,10440,5,6,1910,1981,Wd Sdng,Wd Sdng,...,Y,74,0,128,0,0,0,0,5,2009

In [43]:
Ytrain.head()

902     180000
1111    205000
137     171000
1214    134500
60      158000
Name: SalePrice, dtype: int64

In [45]:
from sklearn.tree import DecisionTreeClassifier

In [55]:
model = DecisionTreeClassifier()
model.fit(Xtrain, Ytrain)

ValueError: could not convert string to float: 'Y'

In [56]:
prediction = model.predict(Xtest)

NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [60]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,Exterior2nd,...,GarageCond,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,VinylSd,VinylSd,...,TA,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,MetalSd,MetalSd,...,TA,298,0,0,0,0,0,0,5,2007
2,3,60,68.0,11250,7,5,2001,2002,VinylSd,VinylSd,...,TA,0,42,0,0,0,0,0,9,2008
3,4,70,60.0,9550,7,5,1915,1970,Wd Sdng,Wd Shng,...,TA,0,35,272,0,0,0,0,2,2006
4,5,60,84.0,14260,8,5,2000,2000,VinylSd,VinylSd,...,TA,192,84,0,0,0,0,0,12,2008

In [61]:
del data['Exterior1st']

In [62]:
del data['Exterior2nd']

In [63]:
del data['GarageCond']

In [64]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrType,MasVnrArea,...,GarageQual,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,BrkFace,196.0,...,TA,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,None,0.0,...,TA,298,0,0,0,0,0,0,5,2007
2,3,60,68.0,11250,7,5,2001,2002,BrkFace,162.0,...,TA,0,42,0,0,0,0,0,9,2008
3,4,70,60.0,9550,7,5,1915,1970,None,0.0,...,TA,0,35,272,0,0,0,0,2,2006
4,5,60,84.0,14260,8,5,2000,2000,BrkFace,350.0,...,TA,192,84,0,0,0,0,0,12,2008

In [65]:
del data['MasVnrType']

In [66]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,...,GarageQual,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,196.0,Gd,...,TA,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,0.0,TA,...,TA,298,0,0,0,0,0,0,5,2007
2,3,60,68.0,11250,7,5,2001,2002,162.0,Gd,...,TA,0,42,0,0,0,0,0,9,2008
3,4,70,60.0,9550,7,5,1915,1970,0.0,TA,...,TA,0,35,272,0,0,0,0,2,2006
4,5,60,84.0,14260,8,5,2000,2000,350.0,Gd,...,TA,192,84,0,0,0,0,0,12,2008

In [68]:
del data['ExterQual']

In [69]:
del data['GarageQual']

In [70]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterCond,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,196.0,TA,...,548,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,0.0,TA,...,460,298,0,0,0,0,0,0,5,2007
2,3,60,68.0,11250,7,5,2001,2002,162.0,TA,...,608,0,42,0,0,0,0,0,9,2008
3,4,70,60.0,9550,7,5,1915,1970,0.0,TA,...,642,0,35,272,0,0,0,0,2,2006
4,5,60,84.0,14260,8,5,2000,2000,350.0,TA,...,836,192,84,0,0,0,0,0,12,2008

In [71]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterCond,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,196.0,TA,...,548,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,0.0,TA,...,460,298,0,0,0,0,0,0,5,2007
2,3,60,68.0,11250,7,5,2001,2002,162.0,TA,...,608,0,42,0,0,0,0,0,9,2008
3,4,70,60.0,9550,7,5,1915,1970,0.0,TA,...,642,0,35,272,0,0,0,0,2,2006
4,5,60,84.0,14260,8,5,2000,2000,350.0,TA,...,836,192,84,0,0,0,0,0,12,2008

In [74]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,Foundation,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,196.0,PConc,...,548,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,0.0,CBlock,...,460,298,0,0,0,0,0,0,5,2007
2,3,60,68.0,11250,7,5,2001,2002,162.0,PConc,...,608,0,42,0,0,0,0,0,9,2008
3,4,70,60.0,9550,7,5,1915,1970,0.0,BrkTil,...,642,0,35,272,0,0,0,0,2,2006
4,5,60,84.0,14260,8,5,2000,2000,350.0,PConc,...,836,192,84,0,0,0,0,0,12,2008

In [82]:
del data ['GarageQual']
del data ['GarageCond']
del data ['PavedDrive']

KeyError: 'GarageQual'

In [84]:
del data['GarageFinish']
del data['GarageType']
del data['Functional']
del data['KitchenQual']
del data['Heating']
del data['HeatingQC']
del data['CentralAir']
del data['Electrical']
del data['BsmtFinType2']
del data['ExterQual']
del data['ExterCond']
del data['Foundation']
del data['BsmtQual']
del data['BsmtCond']
del data['BsmtExposure']
del data['BsmtFinType1']

KeyError: 'GarageFinish'

In [87]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtQual,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,196.0,Gd,...,548,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,0.0,Gd,...,460,298,0,0,0,0,0,0,5,2007
2,3,60,68.0,11250,7,5,2001,2002,162.0,Gd,...,608,0,42,0,0,0,0,0,9,2008
3,4,70,60.0,9550,7,5,1915,1970,0.0,TA,...,642,0,35,272,0,0,0,0,2,2006
4,5,60,84.0,14260,8,5,2000,2000,350.0,Gd,...,836,192,84,0,0,0,0,0,12,2008

In [88]:
del data['BsmtQual']

In [89]:
del data['BsmtCond']

In [90]:
del data['BsmtExposure']

In [91]:
del data['BsmtFinType1']

In [93]:
data.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,548,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,460,298,0,0,0,0,0,0,5,2007
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,608,0,42,0,0,0,0,0,9,2008
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,642,0,35,272,0,0,0,0,2,2006
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,836,192,84,0,0,0,0,0,12,2008

In [94]:
from sklearn.tree import DecisionTreeClassifier

In [95]:
model = DecisionTreeClassifier()
model.fit(Xtrain, Ytrain)

ValueError: could not convert string to float: 'Y'

In [96]:
Ytrain.head()

902     180000
1111    205000
137     171000
1214    134500
60      158000
Name: SalePrice, dtype: int64

In [98]:
data.columns

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold'],
      dtype='object')

In [99]:
del data ['LotFrontage']

In [100]:
del data ['BsmtFinSF2']

In [103]:
model = DecisionTreeClassifier()
model.fit(Xtrain,Ytrain)

ValueError: could not convert string to float: 'Y'

In [104]:
Xtrain.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,Exterior2nd,...,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
902,903,60,63.0,7875,7,5,2003,2003,VinylSd,VinylSd,...,Y,0,75,0,0,0,0,0,7,2006
1111,1112,60,80.0,10480,7,6,1976,1976,Plywood,Plywood,...,Y,0,69,0,0,0,0,0,9,2008
137,138,90,82.0,11070,7,5,1988,1989,VinylSd,VinylSd,...,Y,0,0,0,0,0,0,0,7,2006
1214,1215,85,69.0,10205,5,5,1962,1962,MetalSd,MetalSd,...,Y,150,72,0,0,0,0,0,5,2006
60,61,20,63.0,13072,6,5,2004,2004,VinylSd,VinylSd,...,Y,0,50,0,0,0,0,0,5,2006

In [107]:
Ytrain.head()

902     180000
1111    205000
137     171000
1214    134500
60      158000
Name: SalePrice, dtype: int64